/*
 * Generated by JasperReports - 2/17/17 12:20 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class BorangPenyerahanSewa_1487305206588_598946 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_tarikh_dari = null;
    private JRFillParameter parameter_idPegawai = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_ReportDir = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_tarikh_hingga = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_idModBayaran = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_USER_ID = null;
    private JRFillField field_TARIKH_CEK = null;
    private JRFillField field_NO_FAIL = null;
    private JRFillField field_PENGENALAN = null;
    private JRFillField field_KREDIT = null;
    private JRFillField field_NO_RUJUKAN = null;
    private JRFillField field_NAMA = null;
    private JRFillField field_TARIKH = null;
    private JRFillField field_USER_NAME = null;
    private JRFillField field_FLAG_SUBURUSAN = null;
    private JRFillField field_CATATAN = null;
    private JRFillField field_FLAG_TUNGGAKAN = null;
    private JRFillField field_MAKLUMAT_LOT = null;
    private JRFillField field_KETERANGAN = null;
    private JRFillField field_ID_JENISBAYARAN = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_TOTAL_TANAH = null;
    private JRFillVariable variable_TOTAL_BANGUNAN = null;
    private JRFillVariable variable_COUNT_CEK = null;
    private JRFillVariable variable_TOTAL_AMAUN = null;
    private JRFillVariable variable_TOTAL_TUNGGAK = null;
    private JRFillVariable variable_TOTAL_SEMASA = null;
    private JRFillVariable variable_TOTAL_DEPOSIT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_tarikh_dari = (JRFillParameter)pm.get("tarikh_dari");
        parameter_idPegawai = (JRFillParameter)pm.get("idPegawai");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_ReportDir = (JRFillParameter)pm.get("ReportDir");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_tarikh_hingga = (JRFillParameter)pm.get("tarikh_hingga");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_idModBayaran = (JRFillParameter)pm.get("idModBayaran");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_USER_ID = (JRFillField)fm.get("USER_ID");
        field_TARIKH_CEK = (JRFillField)fm.get("TARIKH_CEK");
        field_NO_FAIL = (JRFillField)fm.get("NO_FAIL");
        field_PENGENALAN = (JRFillField)fm.get("PENGENALAN");
        field_KREDIT = (JRFillField)fm.get("KREDIT");
        field_NO_RUJUKAN = (JRFillField)fm.get("NO_RUJUKAN");
        field_NAMA = (JRFillField)fm.get("NAMA");
        field_TARIKH = (JRFillField)fm.get("TARIKH");
        field_USER_NAME = (JRFillField)fm.get("USER_NAME");
        field_FLAG_SUBURUSAN = (JRFillField)fm.get("FLAG_SUBURUSAN");
        field_CATATAN = (JRFillField)fm.get("CATATAN");
        field_FLAG_TUNGGAKAN = (JRFillField)fm.get("FLAG_TUNGGAKAN");
        field_MAKLUMAT_LOT = (JRFillField)fm.get("MAKLUMAT_LOT");
        field_KETERANGAN = (JRFillField)fm.get("KETERANGAN");
        field_ID_JENISBAYARAN = (JRFillField)fm.get("ID_JENISBAYARAN");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_TOTAL_TANAH = (JRFillVariable)vm.get("TOTAL_TANAH");
        variable_TOTAL_BANGUNAN = (JRFillVariable)vm.get("TOTAL_BANGUNAN");
        variable_COUNT_CEK = (JRFillVariable)vm.get("COUNT_CEK");
        variable_TOTAL_AMAUN = (JRFillVariable)vm.get("TOTAL_AMAUN");
        variable_TOTAL_TUNGGAK = (JRFillVariable)vm.get("TOTAL_TUNGGAK");
        variable_TOTAL_SEMASA = (JRFillVariable)vm.get("TOTAL_SEMASA");
        variable_TOTAL_DEPOSIT = (JRFillVariable)vm.get("TOTAL_DEPOSIT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("T") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_USER_ID.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_KREDIT.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("T")) ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==9 ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_TARIKH.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)((((java.lang.String)field_NAMA.getValue())==null? " " : ((java.lang.String)field_NAMA.getValue()).trim()) + "\n"//$JR_EXPR_ID=23$
+(((java.lang.String)field_PENGENALAN.getValue())==null? " " : ((java.lang.String)field_PENGENALAN.getValue()).trim())  + "\n"//$JR_EXPR_ID=23$
+(((java.lang.String)field_NO_FAIL.getValue())==null? " " : ((java.lang.String)field_NO_FAIL.getValue()).trim())  + "\n"//$JR_EXPR_ID=23$
+ (((java.lang.String)field_MAKLUMAT_LOT.getValue())==null? " " : ((java.lang.String)field_MAKLUMAT_LOT.getValue()).trim()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_NO_RUJUKAN.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_KREDIT.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_TARIKH_CEK.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_CATATAN.getValue()).trim());//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("T") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("Y")) ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("T") && (((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()!=9) ) ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==9 ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)((((java.lang.String)field_KETERANGAN.getValue()) == null ? " " : ((java.lang.String)field_KETERANGAN.getValue()).trim())+ "\n");//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)((((java.lang.String)field_USER_NAME.getValue()) == null ? " " : ((java.lang.String)field_USER_NAME.getValue()).trim()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)("KETUA PEMBANTU TADBIR");//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)("NORIZA BINTI GHAZALI");//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)("PENOLONG PENGARAH");//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)("MOHD 'IZZAT BIN MOHD JAHINI");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_AMAUN.getValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_TANAH.getValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_BANGUNAN.getValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_TUNGGAK.getValue()));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_SEMASA.getValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(((java.lang.Integer)variable_COUNT_CEK.getValue())+ " KEPING CEK");//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_DEPOSIT.getValue()));//$JR_EXPR_ID=75$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getOldValue()).equals("T") ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getOldValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_USER_ID.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_KREDIT.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)((((java.lang.String)field_FLAG_TUNGGAKAN.getOldValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((((java.lang.String)field_FLAG_TUNGGAKAN.getOldValue()).equals("T")) ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()==9 ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_TARIKH.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)((((java.lang.String)field_NAMA.getOldValue())==null? " " : ((java.lang.String)field_NAMA.getOldValue()).trim()) + "\n"//$JR_EXPR_ID=23$
+(((java.lang.String)field_PENGENALAN.getOldValue())==null? " " : ((java.lang.String)field_PENGENALAN.getOldValue()).trim())  + "\n"//$JR_EXPR_ID=23$
+(((java.lang.String)field_NO_FAIL.getOldValue())==null? " " : ((java.lang.String)field_NO_FAIL.getOldValue()).trim())  + "\n"//$JR_EXPR_ID=23$
+ (((java.lang.String)field_MAKLUMAT_LOT.getOldValue())==null? " " : ((java.lang.String)field_MAKLUMAT_LOT.getOldValue()).trim()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_NO_RUJUKAN.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_KREDIT.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_TARIKH_CEK.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_CATATAN.getOldValue()).trim());//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getOldValue()).equals("T") ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getOldValue()).equals("Y")) ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((((java.lang.String)field_FLAG_TUNGGAKAN.getOldValue()).equals("T") && (((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()!=9) ) ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)((((java.lang.String)field_FLAG_TUNGGAKAN.getOldValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getOldValue()).intValue()==9 ? ((java.math.BigDecimal)field_KREDIT.getOldValue()) : null));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)((((java.lang.String)field_KETERANGAN.getOldValue()) == null ? " " : ((java.lang.String)field_KETERANGAN.getOldValue()).trim())+ "\n");//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)((((java.lang.String)field_USER_NAME.getOldValue()) == null ? " " : ((java.lang.String)field_USER_NAME.getOldValue()).trim()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)("KETUA PEMBANTU TADBIR");//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)("NORIZA BINTI GHAZALI");//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)("PENOLONG PENGARAH");//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)("MOHD 'IZZAT BIN MOHD JAHINI");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_AMAUN.getOldValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_TANAH.getOldValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_BANGUNAN.getOldValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_TUNGGAK.getOldValue()));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_SEMASA.getOldValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(((java.lang.Integer)variable_COUNT_CEK.getOldValue())+ " KEPING CEK");//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_DEPOSIT.getOldValue()));//$JR_EXPR_ID=75$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("T") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.math.BigDecimal)field_USER_ID.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_KREDIT.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("T")) ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==9 ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.00));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_TARIKH.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)((((java.lang.String)field_NAMA.getValue())==null? " " : ((java.lang.String)field_NAMA.getValue()).trim()) + "\n"//$JR_EXPR_ID=23$
+(((java.lang.String)field_PENGENALAN.getValue())==null? " " : ((java.lang.String)field_PENGENALAN.getValue()).trim())  + "\n"//$JR_EXPR_ID=23$
+(((java.lang.String)field_NO_FAIL.getValue())==null? " " : ((java.lang.String)field_NO_FAIL.getValue()).trim())  + "\n"//$JR_EXPR_ID=23$
+ (((java.lang.String)field_MAKLUMAT_LOT.getValue())==null? " " : ((java.lang.String)field_MAKLUMAT_LOT.getValue()).trim()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.String)(((java.lang.String)field_NO_RUJUKAN.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_KREDIT.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.sql.Timestamp)(((java.sql.Timestamp)field_TARIKH_CEK.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.String)(((java.lang.String)field_CATATAN.getValue()).trim());//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("T") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.math.BigDecimal)(((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==10 && ((java.lang.String)field_FLAG_SUBURUSAN.getValue()).equals("Y")) ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("T") && (((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()!=9) ) ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)((((java.lang.String)field_FLAG_TUNGGAKAN.getValue()).equals("Y") ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.math.BigDecimal)((((java.math.BigDecimal)field_ID_JENISBAYARAN.getValue()).intValue()==9 ? ((java.math.BigDecimal)field_KREDIT.getValue()) : null));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)((((java.lang.String)field_KETERANGAN.getValue()) == null ? " " : ((java.lang.String)field_KETERANGAN.getValue()).trim())+ "\n");//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)((((java.lang.String)field_USER_NAME.getValue()) == null ? " " : ((java.lang.String)field_USER_NAME.getValue()).trim()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.String)("KETUA PEMBANTU TADBIR");//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)("NORIZA BINTI GHAZALI");//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.String)("PENOLONG PENGARAH");//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.String)("MOHD 'IZZAT BIN MOHD JAHINI");//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.String)(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.String)("Tarikh");//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.String)("Nama");//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.String)("Jawatan");//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=65$
                break;
            }
            case 66 : 
            {
                value = (java.lang.String)(":");//$JR_EXPR_ID=66$
                break;
            }
            case 67 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=67$
                break;
            }
            case 68 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=68$
                break;
            }
            case 69 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_AMAUN.getEstimatedValue()));//$JR_EXPR_ID=69$
                break;
            }
            case 70 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_TANAH.getEstimatedValue()));//$JR_EXPR_ID=70$
                break;
            }
            case 71 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_BANGUNAN.getEstimatedValue()));//$JR_EXPR_ID=71$
                break;
            }
            case 72 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_TUNGGAK.getEstimatedValue()));//$JR_EXPR_ID=72$
                break;
            }
            case 73 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_SEMASA.getEstimatedValue()));//$JR_EXPR_ID=73$
                break;
            }
            case 74 : 
            {
                value = (java.lang.String)(((java.lang.Integer)variable_COUNT_CEK.getEstimatedValue())+ " KEPING CEK");//$JR_EXPR_ID=74$
                break;
            }
            case 75 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_TOTAL_DEPOSIT.getEstimatedValue()));//$JR_EXPR_ID=75$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
