/*
 * Generated by JasperReports - 12/16/16 11:14 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class BorangT3_1481858050267_465019 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_kpPemohon = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_ReportDir = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_namaPegawai = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_alamatPemohon = null;
    private JRFillParameter parameter_jawatan = null;
    private JRFillParameter parameter_idfail = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_namaPemohon = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_HARI_BICARA = null;
    private JRFillField field_ID_PERBICARAAN = null;
    private JRFillField field_KP_PEMOHON = null;
    private JRFillField field_ID_FAIL = null;
    private JRFillField field_NO_FAIL = null;
    private JRFillField field_TARIKH_MATI = null;
    private JRFillField field_ALAMAT_PENUH_PEMOHON = null;
    private JRFillField field_TAHUN_NO_FAIL = null;
    private JRFillField field_NAMA_SIMATI = null;
    private JRFillField field_TAHUN = null;
    private JRFillField field_KP_SIMATI = null;
    private JRFillField field_ID_PERINTAHHTAOBMST = null;
    private JRFillField field_TAHUN_BICARA = null;
    private JRFillField field_BUKTI_MATI = null;
    private JRFillField field_ID_PERINTAHHAOBMST = null;
    private JRFillField field_ID_PERINTAH = null;
    private JRFillField field_CATATAN = null;
    private JRFillField field_BULAN_BICARA = null;
    private JRFillField field_NAMA_PEMOHON = null;
    private JRFillField field_NAMA_NEGERI = null;
    private JRFillField field_ID_PERMOHONAN = null;
    private JRFillField field_NAMA_DAERAH = null;
    private JRFillField field_ID_KEPUTUSANPERMOHONAN = null;
    private JRFillField field_NO_SIJIL_MATI = null;
    private JRFillField field_ID_SIMATI = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_kpPemohon = (JRFillParameter)pm.get("kpPemohon");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_ReportDir = (JRFillParameter)pm.get("ReportDir");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_namaPegawai = (JRFillParameter)pm.get("namaPegawai");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_alamatPemohon = (JRFillParameter)pm.get("alamatPemohon");
        parameter_jawatan = (JRFillParameter)pm.get("jawatan");
        parameter_idfail = (JRFillParameter)pm.get("idfail");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_namaPemohon = (JRFillParameter)pm.get("namaPemohon");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_HARI_BICARA = (JRFillField)fm.get("HARI_BICARA");
        field_ID_PERBICARAAN = (JRFillField)fm.get("ID_PERBICARAAN");
        field_KP_PEMOHON = (JRFillField)fm.get("KP_PEMOHON");
        field_ID_FAIL = (JRFillField)fm.get("ID_FAIL");
        field_NO_FAIL = (JRFillField)fm.get("NO_FAIL");
        field_TARIKH_MATI = (JRFillField)fm.get("TARIKH_MATI");
        field_ALAMAT_PENUH_PEMOHON = (JRFillField)fm.get("ALAMAT_PENUH_PEMOHON");
        field_TAHUN_NO_FAIL = (JRFillField)fm.get("TAHUN_NO_FAIL");
        field_NAMA_SIMATI = (JRFillField)fm.get("NAMA_SIMATI");
        field_TAHUN = (JRFillField)fm.get("TAHUN");
        field_KP_SIMATI = (JRFillField)fm.get("KP_SIMATI");
        field_ID_PERINTAHHTAOBMST = (JRFillField)fm.get("ID_PERINTAHHTAOBMST");
        field_TAHUN_BICARA = (JRFillField)fm.get("TAHUN_BICARA");
        field_BUKTI_MATI = (JRFillField)fm.get("BUKTI_MATI");
        field_ID_PERINTAHHAOBMST = (JRFillField)fm.get("ID_PERINTAHHAOBMST");
        field_ID_PERINTAH = (JRFillField)fm.get("ID_PERINTAH");
        field_CATATAN = (JRFillField)fm.get("CATATAN");
        field_BULAN_BICARA = (JRFillField)fm.get("BULAN_BICARA");
        field_NAMA_PEMOHON = (JRFillField)fm.get("NAMA_PEMOHON");
        field_NAMA_NEGERI = (JRFillField)fm.get("NAMA_NEGERI");
        field_ID_PERMOHONAN = (JRFillField)fm.get("ID_PERMOHONAN");
        field_NAMA_DAERAH = (JRFillField)fm.get("NAMA_DAERAH");
        field_ID_KEPUTUSANPERMOHONAN = (JRFillField)fm.get("ID_KEPUTUSANPERMOHONAN");
        field_NO_SIJIL_MATI = (JRFillField)fm.get("NO_SIJIL_MATI");
        field_ID_SIMATI = (JRFillField)fm.get("ID_SIMATI");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_NO_FAIL.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERMOHONAN.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreport0.jasper");//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("<style isBold='true' pdfFontName='Helvetica-Bold'>"+"BORANG T"+"</style>"//$JR_EXPR_ID=16$
+"\n(Peraturan 12(3))"//$JR_EXPR_ID=16$
+"\n<style isBold='true' pdfFontName='Helvetica-Bold'>"+"MALAYSIA"+"</style>"//$JR_EXPR_ID=16$
+"\nNegeri <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NAMA_NEGERI.getValue())!= null ? ((java.lang.String)field_NAMA_NEGERI.getValue()):"TIADA")+"</style>"//$JR_EXPR_ID=16$
+"\nDaerah <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NAMA_DAERAH.getValue())!= null ? ((java.lang.String)field_NAMA_DAERAH.getValue()):"TIADA")+"</style>"//$JR_EXPR_ID=16$
+"\n\n<style isBold='true' pdfFontName='Helvetica-Bold'>"+"AKTA HARTA PUSAKA KECIL (PEMBAHAGIAN), 1955"+"</style>"//$JR_EXPR_ID=16$
+"\n\nGUAMAN PEMBAHAGIAN NO. <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NO_FAIL.getValue())!= null ? ((java.lang.String)field_NO_FAIL.getValue()):"TIADA")+"</style> TAHUN <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_TAHUN.getValue())!= null ? ((java.lang.String)field_TAHUN.getValue()):"TIADA")+"</style>");//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Boolean)(new Boolean ((!((java.lang.String)field_ID_PERINTAHHTAOBMST.getValue()).equals("0"))));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_HARI_BICARA.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BULAN_BICARA.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_NAMA_NEGERI.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_TAHUN_BICARA.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERINTAH.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreportHTA.jasper");//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.Boolean)(new Boolean ((!((java.lang.String)field_ID_PERINTAHHAOBMST.getValue()).equals("0"))));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_HARI_BICARA.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BULAN_BICARA.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_NAMA_NEGERI.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_TAHUN_BICARA.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERINTAH.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreportHA.jasper");//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)("Dalam hal Harta Pusaka <style isBold='true' pdfFontName='Helvetica-Bold'>"+ ((java.lang.String)field_NAMA_SIMATI.getValue())+", No. KP: "+(((java.lang.String)field_KP_SIMATI.getValue())!= null ? ((java.lang.String)field_KP_SIMATI.getValue()):"TIADA")+", Tarikh mati: "+(((java.lang.String)field_TARIKH_MATI.getValue())!= null ? ((java.lang.String)field_TARIKH_MATI.getValue()):"TIADA")+(((java.lang.String)field_BUKTI_MATI.getValue())!=null?((java.lang.String)field_BUKTI_MATI.getValue()):"")+".</style>"//$JR_EXPR_ID=41$
+"\n\nPetisyen daripada <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)parameter_namaPemohon.getValue())!= null ? ((java.lang.String)parameter_namaPemohon.getValue()):"TIADA") + (((java.lang.String)parameter_kpPemohon.getValue())!= "" ?", No. KP: "+ ((java.lang.String)parameter_kpPemohon.getValue()):"")+"</style> yang beralamat di <style isBold='true' pdfFontName='Helvetica-Bold'>"+ (((java.lang.String)parameter_alamatPemohon.getValue())!= null ? ((java.lang.String)parameter_alamatPemohon.getValue()):"TIADA")+"</style>."//$JR_EXPR_ID=41$
+"\n\n                                            <style isBold='true' pdfFontName='Helvetica-Bold'>PERINTAH ATAS PERMOHONAN YANG BERIKUTNYA</style>"//$JR_EXPR_ID=41$
+"\n                                                                               (Seksyen 17)"//$JR_EXPR_ID=41$
+"\n\nBAHAWASANYA permohonan telah dibuat oleh <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)field_NAMA_PEMOHON.getValue())!= null ? ((java.lang.String)field_NAMA_PEMOHON.getValue()):"TIADA") + ", No. KP: " +(((java.lang.String)field_KP_PEMOHON.getValue())!= null ? ((java.lang.String)field_KP_PEMOHON.getValue()):"TIADA")+"</style> yang beralamat di <style isBold='true' pdfFontName='Helvetica-Bold'>" +(((java.lang.String)field_ALAMAT_PENUH_PEMOHON.getValue())!= null ? ((java.lang.String)field_ALAMAT_PENUH_PEMOHON.getValue()):"TIADA")+ "</style> bagi suatu perintah selanjutnya dalam Guaman yang tersebut di atas."//$JR_EXPR_ID=41$
+"\n\n        OLEH YANG DEMIKIAN SAYA, <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)parameter_namaPegawai.getValue())!= null ? ((java.lang.String)parameter_namaPegawai.getValue()):"TIADA") + " "+ (((java.lang.String)parameter_jawatan.getValue())!= null ? "*"+((java.lang.String)parameter_jawatan.getValue()):"TIADA")+"</style> BAGI DAERAH <style isBold='true' pdfFontName='Helvetica-Bold'>"+ (((java.lang.String)field_NAMA_DAERAH.getValue())!= null ? ((java.lang.String)field_NAMA_DAERAH.getValue()):"TIADA")+ "</style> DENGAN INI MEMERINTAHKAN BAHAWA <style isBold='true' pdfFontName='Helvetica-Bold'>" +(((java.lang.String)field_CATATAN.getValue())!=null?((java.lang.String)field_CATATAN.getValue()):"")+"</style>"//$JR_EXPR_ID=41$
+"\n\nDi buat pada <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)field_HARI_BICARA.getValue())!= null ? ((java.lang.String)field_HARI_BICARA.getValue()):"TIADA")+"</style> haribulan <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_BULAN_BICARA.getValue())!= null ? ((java.lang.String)field_BULAN_BICARA.getValue()):"TIADA")+ " " + ((java.lang.String)field_TAHUN_BICARA.getValue()) +"</style>");//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("                                                                   T.M ................................................................."//$JR_EXPR_ID=42$
+"\n                                                                                    PENTADBIR TANAH / PEMUNGUT/"//$JR_EXPR_ID=42$
+"\n                                                                                    PEGAWAI DAERAH / PEGAWAI"//$JR_EXPR_ID=42$
+"\n                                                                                    PENTADBIR SARAWAK");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(" Mukasurat " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " dari ");//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(" "+((java.lang.Integer)variable_PAGE_NUMBER.getValue())+"");//$JR_EXPR_ID=44$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_NO_FAIL.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERMOHONAN.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreport0.jasper");//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("<style isBold='true' pdfFontName='Helvetica-Bold'>"+"BORANG T"+"</style>"//$JR_EXPR_ID=16$
+"\n(Peraturan 12(3))"//$JR_EXPR_ID=16$
+"\n<style isBold='true' pdfFontName='Helvetica-Bold'>"+"MALAYSIA"+"</style>"//$JR_EXPR_ID=16$
+"\nNegeri <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NAMA_NEGERI.getOldValue())!= null ? ((java.lang.String)field_NAMA_NEGERI.getOldValue()):"TIADA")+"</style>"//$JR_EXPR_ID=16$
+"\nDaerah <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NAMA_DAERAH.getOldValue())!= null ? ((java.lang.String)field_NAMA_DAERAH.getOldValue()):"TIADA")+"</style>"//$JR_EXPR_ID=16$
+"\n\n<style isBold='true' pdfFontName='Helvetica-Bold'>"+"AKTA HARTA PUSAKA KECIL (PEMBAHAGIAN), 1955"+"</style>"//$JR_EXPR_ID=16$
+"\n\nGUAMAN PEMBAHAGIAN NO. <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NO_FAIL.getOldValue())!= null ? ((java.lang.String)field_NO_FAIL.getOldValue()):"TIADA")+"</style> TAHUN <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_TAHUN.getOldValue())!= null ? ((java.lang.String)field_TAHUN.getOldValue()):"TIADA")+"</style>");//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Boolean)(new Boolean ((!((java.lang.String)field_ID_PERINTAHHTAOBMST.getOldValue()).equals("0"))));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_HARI_BICARA.getOldValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BULAN_BICARA.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_NAMA_NEGERI.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_TAHUN_BICARA.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERINTAH.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreportHTA.jasper");//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.Boolean)(new Boolean ((!((java.lang.String)field_ID_PERINTAHHAOBMST.getOldValue()).equals("0"))));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_HARI_BICARA.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BULAN_BICARA.getOldValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_NAMA_NEGERI.getOldValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_TAHUN_BICARA.getOldValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERINTAH.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreportHA.jasper");//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)("Dalam hal Harta Pusaka <style isBold='true' pdfFontName='Helvetica-Bold'>"+ ((java.lang.String)field_NAMA_SIMATI.getOldValue())+", No. KP: "+(((java.lang.String)field_KP_SIMATI.getOldValue())!= null ? ((java.lang.String)field_KP_SIMATI.getOldValue()):"TIADA")+", Tarikh mati: "+(((java.lang.String)field_TARIKH_MATI.getOldValue())!= null ? ((java.lang.String)field_TARIKH_MATI.getOldValue()):"TIADA")+(((java.lang.String)field_BUKTI_MATI.getOldValue())!=null?((java.lang.String)field_BUKTI_MATI.getOldValue()):"")+".</style>"//$JR_EXPR_ID=41$
+"\n\nPetisyen daripada <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)parameter_namaPemohon.getValue())!= null ? ((java.lang.String)parameter_namaPemohon.getValue()):"TIADA") + (((java.lang.String)parameter_kpPemohon.getValue())!= "" ?", No. KP: "+ ((java.lang.String)parameter_kpPemohon.getValue()):"")+"</style> yang beralamat di <style isBold='true' pdfFontName='Helvetica-Bold'>"+ (((java.lang.String)parameter_alamatPemohon.getValue())!= null ? ((java.lang.String)parameter_alamatPemohon.getValue()):"TIADA")+"</style>."//$JR_EXPR_ID=41$
+"\n\n                                            <style isBold='true' pdfFontName='Helvetica-Bold'>PERINTAH ATAS PERMOHONAN YANG BERIKUTNYA</style>"//$JR_EXPR_ID=41$
+"\n                                                                               (Seksyen 17)"//$JR_EXPR_ID=41$
+"\n\nBAHAWASANYA permohonan telah dibuat oleh <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)field_NAMA_PEMOHON.getOldValue())!= null ? ((java.lang.String)field_NAMA_PEMOHON.getOldValue()):"TIADA") + ", No. KP: " +(((java.lang.String)field_KP_PEMOHON.getOldValue())!= null ? ((java.lang.String)field_KP_PEMOHON.getOldValue()):"TIADA")+"</style> yang beralamat di <style isBold='true' pdfFontName='Helvetica-Bold'>" +(((java.lang.String)field_ALAMAT_PENUH_PEMOHON.getOldValue())!= null ? ((java.lang.String)field_ALAMAT_PENUH_PEMOHON.getOldValue()):"TIADA")+ "</style> bagi suatu perintah selanjutnya dalam Guaman yang tersebut di atas."//$JR_EXPR_ID=41$
+"\n\n        OLEH YANG DEMIKIAN SAYA, <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)parameter_namaPegawai.getValue())!= null ? ((java.lang.String)parameter_namaPegawai.getValue()):"TIADA") + " "+ (((java.lang.String)parameter_jawatan.getValue())!= null ? "*"+((java.lang.String)parameter_jawatan.getValue()):"TIADA")+"</style> BAGI DAERAH <style isBold='true' pdfFontName='Helvetica-Bold'>"+ (((java.lang.String)field_NAMA_DAERAH.getOldValue())!= null ? ((java.lang.String)field_NAMA_DAERAH.getOldValue()):"TIADA")+ "</style> DENGAN INI MEMERINTAHKAN BAHAWA <style isBold='true' pdfFontName='Helvetica-Bold'>" +(((java.lang.String)field_CATATAN.getOldValue())!=null?((java.lang.String)field_CATATAN.getOldValue()):"")+"</style>"//$JR_EXPR_ID=41$
+"\n\nDi buat pada <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)field_HARI_BICARA.getOldValue())!= null ? ((java.lang.String)field_HARI_BICARA.getOldValue()):"TIADA")+"</style> haribulan <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_BULAN_BICARA.getOldValue())!= null ? ((java.lang.String)field_BULAN_BICARA.getOldValue()):"TIADA")+ " " + ((java.lang.String)field_TAHUN_BICARA.getOldValue()) +"</style>");//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("                                                                   T.M ................................................................."//$JR_EXPR_ID=42$
+"\n                                                                                    PENTADBIR TANAH / PEMUNGUT/"//$JR_EXPR_ID=42$
+"\n                                                                                    PEGAWAI DAERAH / PEGAWAI"//$JR_EXPR_ID=42$
+"\n                                                                                    PENTADBIR SARAWAK");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(" Mukasurat " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " dari ");//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(" "+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+"");//$JR_EXPR_ID=44$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.String)(((java.lang.String)field_NO_FAIL.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERMOHONAN.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreport0.jasper");//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("<style isBold='true' pdfFontName='Helvetica-Bold'>"+"BORANG T"+"</style>"//$JR_EXPR_ID=16$
+"\n(Peraturan 12(3))"//$JR_EXPR_ID=16$
+"\n<style isBold='true' pdfFontName='Helvetica-Bold'>"+"MALAYSIA"+"</style>"//$JR_EXPR_ID=16$
+"\nNegeri <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NAMA_NEGERI.getValue())!= null ? ((java.lang.String)field_NAMA_NEGERI.getValue()):"TIADA")+"</style>"//$JR_EXPR_ID=16$
+"\nDaerah <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NAMA_DAERAH.getValue())!= null ? ((java.lang.String)field_NAMA_DAERAH.getValue()):"TIADA")+"</style>"//$JR_EXPR_ID=16$
+"\n\n<style isBold='true' pdfFontName='Helvetica-Bold'>"+"AKTA HARTA PUSAKA KECIL (PEMBAHAGIAN), 1955"+"</style>"//$JR_EXPR_ID=16$
+"\n\nGUAMAN PEMBAHAGIAN NO. <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_NO_FAIL.getValue())!= null ? ((java.lang.String)field_NO_FAIL.getValue()):"TIADA")+"</style> TAHUN <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_TAHUN.getValue())!= null ? ((java.lang.String)field_TAHUN.getValue()):"TIADA")+"</style>");//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Boolean)(new Boolean ((!((java.lang.String)field_ID_PERINTAHHTAOBMST.getValue()).equals("0"))));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_HARI_BICARA.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BULAN_BICARA.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_NAMA_NEGERI.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_TAHUN_BICARA.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERINTAH.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreportHTA.jasper");//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.Boolean)(new Boolean ((!((java.lang.String)field_ID_PERINTAHHAOBMST.getValue()).equals("0"))));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_HARI_BICARA.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_jawatan.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_idfail.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_BULAN_BICARA.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_namaPegawai.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_NAMA_NEGERI.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_TAHUN_BICARA.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_ID_PERINTAH.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\BorangT2_subreportHA.jasper");//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)("Dalam hal Harta Pusaka <style isBold='true' pdfFontName='Helvetica-Bold'>"+ ((java.lang.String)field_NAMA_SIMATI.getValue())+", No. KP: "+(((java.lang.String)field_KP_SIMATI.getValue())!= null ? ((java.lang.String)field_KP_SIMATI.getValue()):"TIADA")+", Tarikh mati: "+(((java.lang.String)field_TARIKH_MATI.getValue())!= null ? ((java.lang.String)field_TARIKH_MATI.getValue()):"TIADA")+(((java.lang.String)field_BUKTI_MATI.getValue())!=null?((java.lang.String)field_BUKTI_MATI.getValue()):"")+".</style>"//$JR_EXPR_ID=41$
+"\n\nPetisyen daripada <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)parameter_namaPemohon.getValue())!= null ? ((java.lang.String)parameter_namaPemohon.getValue()):"TIADA") + (((java.lang.String)parameter_kpPemohon.getValue())!= "" ?", No. KP: "+ ((java.lang.String)parameter_kpPemohon.getValue()):"")+"</style> yang beralamat di <style isBold='true' pdfFontName='Helvetica-Bold'>"+ (((java.lang.String)parameter_alamatPemohon.getValue())!= null ? ((java.lang.String)parameter_alamatPemohon.getValue()):"TIADA")+"</style>."//$JR_EXPR_ID=41$
+"\n\n                                            <style isBold='true' pdfFontName='Helvetica-Bold'>PERINTAH ATAS PERMOHONAN YANG BERIKUTNYA</style>"//$JR_EXPR_ID=41$
+"\n                                                                               (Seksyen 17)"//$JR_EXPR_ID=41$
+"\n\nBAHAWASANYA permohonan telah dibuat oleh <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)field_NAMA_PEMOHON.getValue())!= null ? ((java.lang.String)field_NAMA_PEMOHON.getValue()):"TIADA") + ", No. KP: " +(((java.lang.String)field_KP_PEMOHON.getValue())!= null ? ((java.lang.String)field_KP_PEMOHON.getValue()):"TIADA")+"</style> yang beralamat di <style isBold='true' pdfFontName='Helvetica-Bold'>" +(((java.lang.String)field_ALAMAT_PENUH_PEMOHON.getValue())!= null ? ((java.lang.String)field_ALAMAT_PENUH_PEMOHON.getValue()):"TIADA")+ "</style> bagi suatu perintah selanjutnya dalam Guaman yang tersebut di atas."//$JR_EXPR_ID=41$
+"\n\n        OLEH YANG DEMIKIAN SAYA, <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)parameter_namaPegawai.getValue())!= null ? ((java.lang.String)parameter_namaPegawai.getValue()):"TIADA") + " "+ (((java.lang.String)parameter_jawatan.getValue())!= null ? "*"+((java.lang.String)parameter_jawatan.getValue()):"TIADA")+"</style> BAGI DAERAH <style isBold='true' pdfFontName='Helvetica-Bold'>"+ (((java.lang.String)field_NAMA_DAERAH.getValue())!= null ? ((java.lang.String)field_NAMA_DAERAH.getValue()):"TIADA")+ "</style> DENGAN INI MEMERINTAHKAN BAHAWA <style isBold='true' pdfFontName='Helvetica-Bold'>" +(((java.lang.String)field_CATATAN.getValue())!=null?((java.lang.String)field_CATATAN.getValue()):"")+"</style>"//$JR_EXPR_ID=41$
+"\n\nDi buat pada <style isBold='true' pdfFontName='Helvetica-Bold'>" + (((java.lang.String)field_HARI_BICARA.getValue())!= null ? ((java.lang.String)field_HARI_BICARA.getValue()):"TIADA")+"</style> haribulan <style isBold='true' pdfFontName='Helvetica-Bold'>"+(((java.lang.String)field_BULAN_BICARA.getValue())!= null ? ((java.lang.String)field_BULAN_BICARA.getValue()):"TIADA")+ " " + ((java.lang.String)field_TAHUN_BICARA.getValue()) +"</style>");//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)("                                                                   T.M ................................................................."//$JR_EXPR_ID=42$
+"\n                                                                                    PENTADBIR TANAH / PEMUNGUT/"//$JR_EXPR_ID=42$
+"\n                                                                                    PEGAWAI DAERAH / PEGAWAI"//$JR_EXPR_ID=42$
+"\n                                                                                    PENTADBIR SARAWAK");//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(" Mukasurat " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " dari ");//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.String)(" "+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+"");//$JR_EXPR_ID=44$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
