/*
 * Generated by JasperReports - 12/5/16 10:53 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class LaporanRekodPermohonanDaerahBulanan_1480906403832_394650 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_ID_NEGERI = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_ReportDir = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_LAPORAN = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_TAHUN = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_ID = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_BULAN = null;
    private JRFillParameter parameter_os = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_ID_SUBURUSAN = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_BULANTAHUN = null;
    private JRFillParameter parameter_ID_PEJABAT = null;
    private JRFillParameter parameter_SQLQUERY = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_SEKSYEN = null;
    private JRFillField field_ID_SUBURUSAN = null;
    private JRFillField field_NAMA_DAERAH = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_ID_NEGERI = (JRFillParameter)pm.get("ID_NEGERI");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_ReportDir = (JRFillParameter)pm.get("ReportDir");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_LAPORAN = (JRFillParameter)pm.get("LAPORAN");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_TAHUN = (JRFillParameter)pm.get("TAHUN");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_ID = (JRFillParameter)pm.get("ID");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_BULAN = (JRFillParameter)pm.get("BULAN");
        parameter_os = (JRFillParameter)pm.get("os");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_ID_SUBURUSAN = (JRFillParameter)pm.get("ID_SUBURUSAN");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_BULANTAHUN = (JRFillParameter)pm.get("BULANTAHUN");
        parameter_ID_PEJABAT = (JRFillParameter)pm.get("ID_PEJABAT");
        parameter_SQLQUERY = (JRFillParameter)pm.get("SQLQUERY");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_SEKSYEN = (JRFillParameter)pm.get("SEKSYEN");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ID_SUBURUSAN = (JRFillField)fm.get("ID_SUBURUSAN");
        field_NAMA_DAERAH = (JRFillField)fm.get("NAMA_DAERAH");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("1");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)("REKOD PERMOHONAN SEKSYEN "+ (((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()).intValue()==59?8:17)+" - DAERAH "+ ((java.lang.String)field_NAMA_DAERAH.getValue()).toUpperCase() +" "+  ((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=22$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub165.jasper"//$JR_EXPR_ID=22$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub165.jasper");//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=35$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub135.jasper"//$JR_EXPR_ID=35$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub135.jasper");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=48$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub90.jasper"//$JR_EXPR_ID=48$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub90.jasper");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(" Mukasurat " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " dari ");//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(" "+((java.lang.Integer)variable_PAGE_NUMBER.getValue())+"");//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("REKOD PERMOHONAN SEKSYEN "+ (((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()).intValue()==59?8:17)+" - DAERAH "+ (((java.lang.String)field_NAMA_DAERAH.getValue())==null?"":((java.lang.String)field_NAMA_DAERAH.getValue()).toUpperCase())+" "+  ((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=65$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub90.jasper"//$JR_EXPR_ID=65$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub90.jasper");//$JR_EXPR_ID=65$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("1");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)("REKOD PERMOHONAN SEKSYEN "+ (((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()).intValue()==59?8:17)+" - DAERAH "+ ((java.lang.String)field_NAMA_DAERAH.getOldValue()).toUpperCase() +" "+  ((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=22$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub165.jasper"//$JR_EXPR_ID=22$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub165.jasper");//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=35$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub135.jasper"//$JR_EXPR_ID=35$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub135.jasper");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=48$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub90.jasper"//$JR_EXPR_ID=48$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub90.jasper");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(" Mukasurat " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " dari ");//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(" "+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+"");//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("REKOD PERMOHONAN SEKSYEN "+ (((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()).intValue()==59?8:17)+" - DAERAH "+ (((java.lang.String)field_NAMA_DAERAH.getOldValue())==null?"":((java.lang.String)field_NAMA_DAERAH.getOldValue()).toUpperCase())+" "+  ((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=65$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub90.jasper"//$JR_EXPR_ID=65$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub90.jasper");//$JR_EXPR_ID=65$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("1");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)("REKOD PERMOHONAN SEKSYEN "+ (((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()).intValue()==59?8:17)+" - DAERAH "+ ((java.lang.String)field_NAMA_DAERAH.getValue()).toUpperCase() +" "+  ((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=22$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub165.jasper"//$JR_EXPR_ID=22$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub165.jasper");//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=35$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub135.jasper"//$JR_EXPR_ID=35$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub135.jasper");//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=48$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub90.jasper"//$JR_EXPR_ID=48$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub90.jasper");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.String)(" Mukasurat " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " dari ");//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(" "+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+"");//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.String)("REKOD PERMOHONAN SEKSYEN "+ (((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()).intValue()==59?8:17)+" - DAERAH "+ (((java.lang.String)field_NAMA_DAERAH.getValue())==null?"":((java.lang.String)field_NAMA_DAERAH.getValue()).toUpperCase())+" "+  ((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULAN.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_NEGERI.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_LAPORAN.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SQLQUERY.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_TAHUN.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_SUBURUSAN.getValue()));//$JR_EXPR_ID=58$
                break;
            }
            case 59 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_ReportDir.getValue()));//$JR_EXPR_ID=59$
                break;
            }
            case 60 : 
            {
                value = (java.lang.Object)(""+((java.lang.Integer)parameter_ID.getValue()));//$JR_EXPR_ID=60$
                break;
            }
            case 61 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_BULANTAHUN.getValue()));//$JR_EXPR_ID=61$
                break;
            }
            case 62 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_ID_PEJABAT.getValue()));//$JR_EXPR_ID=62$
                break;
            }
            case 63 : 
            {
                value = (java.lang.Object)(((java.lang.String)parameter_SEKSYEN.getValue()));//$JR_EXPR_ID=63$
                break;
            }
            case 64 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=64$
                break;
            }
            case 65 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_os.getValue()).equals("0")//$JR_EXPR_ID=65$
? ((java.lang.String)parameter_ReportDir.getValue()) + "//ppk//LaporanRekodPermohonanDaerahBulananSub90.jasper"//$JR_EXPR_ID=65$
: ((java.lang.String)parameter_ReportDir.getValue()) + "\\ppk\\LaporanRekodPermohonanDaerahBulananSub90.jasper");//$JR_EXPR_ID=65$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
