/*
 * Generated by JasperReports - 10/25/17 5:36 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class ConditonalFontColor_1508924193481_474035 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_CUSTOMER_ID = null;
    private JRFillField field_STORECOST = null;
    private JRFillField field_STORESALES = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_CUSTOMER_ID = (JRFillField)fm.get("CUSTOMER_ID");
        field_STORECOST = (JRFillField)fm.get("STORECOST");
        field_STORESALES = (JRFillField)fm.get("STORESALES");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_CUSTOMER_ID.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Boolean)(((java.math.BigDecimal)field_STORESALES.getValue())>=30);
        }
        else if (id == 10)
        {
            value = (java.lang.Boolean)(((java.math.BigDecimal)field_STORESALES.getValue())<30);
        }
        else if (id == 11)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_STORESALES.getValue()));
        }
        else if (id == 12)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_STORECOST.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_CUSTOMER_ID.getOldValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Boolean)(((java.math.BigDecimal)field_STORESALES.getOldValue())>=30);
        }
        else if (id == 10)
        {
            value = (java.lang.Boolean)(((java.math.BigDecimal)field_STORESALES.getOldValue())<30);
        }
        else if (id == 11)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_STORESALES.getOldValue()));
        }
        else if (id == 12)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_STORECOST.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 1)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 2)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 3)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 4)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 5)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 6)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_CUSTOMER_ID.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Boolean)(((java.math.BigDecimal)field_STORESALES.getValue())>=30);
        }
        else if (id == 10)
        {
            value = (java.lang.Boolean)(((java.math.BigDecimal)field_STORESALES.getValue())<30);
        }
        else if (id == 11)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_STORESALES.getValue()));
        }
        else if (id == 12)
        {
            value = (java.lang.String)(((java.math.BigDecimal)field_STORECOST.getValue()));
        }

        return value;
    }


}
